/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;

import Back.Control.Files.Export;
import Back.Control.Sort;
import Back.DataEstructure.ListDin;
import Back.DataEstructure.Node;
import Back.Objects.Bet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aguare
 */
public class TableBets extends javax.swing.JFrame {
    
    private ListDin bets;
    private Export export;
    private Sort sort = new Sort();

    /**
     * Creates new form TableBets
     */
    public TableBets(ListDin bets, String title, boolean sortEnabled) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.bets = bets;
        this.export = new Export();
        titleLabel.setText(title);
        orderByNameBtn.setEnabled(sortEnabled);
        orderByPointsBtn.setEnabled(sortEnabled);
        fillTable();
    }
    
    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        Node node = bets.getFirst();
        while (node.getNext()!= null) {
            Bet bet = node.getElement();
            int[] h = bet.getHorses();
            model.addRow(new Object[]{bet.getBettor_name(), bet.getPoints(), bet.getBet_amount(),
                h[0], h[1], h[2], h[3], h[4], h[5], h[6], h[7], h[8], h[9]
            });
            node = node.getNext();
        }
        this.mainTable.setModel(model);
        sizeLabel.setText("" + bets.getSize());
    }
    
    private void cleanTable() {
        DefaultTableModel model = (DefaultTableModel) mainTable.getModel();
        model.getDataVector().removeAllElements();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        exportBtn = new javax.swing.JButton();
        orderByPointsBtn = new javax.swing.JButton();
        orderByNameBtn = new javax.swing.JButton();
        sizeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Puntos", "Apuesta", "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mainTable);
        if (mainTable.getColumnModel().getColumnCount() > 0) {
            mainTable.getColumnModel().getColumn(0).setResizable(false);
            mainTable.getColumnModel().getColumn(1).setResizable(false);
            mainTable.getColumnModel().getColumn(2).setResizable(false);
            mainTable.getColumnModel().getColumn(3).setResizable(false);
            mainTable.getColumnModel().getColumn(4).setResizable(false);
            mainTable.getColumnModel().getColumn(5).setResizable(false);
            mainTable.getColumnModel().getColumn(6).setResizable(false);
            mainTable.getColumnModel().getColumn(7).setResizable(false);
            mainTable.getColumnModel().getColumn(8).setResizable(false);
            mainTable.getColumnModel().getColumn(9).setResizable(false);
            mainTable.getColumnModel().getColumn(10).setResizable(false);
            mainTable.getColumnModel().getColumn(11).setResizable(false);
            mainTable.getColumnModel().getColumn(12).setResizable(false);
        }

        titleLabel.setBackground(new java.awt.Color(63, 76, 135));
        titleLabel.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(254, 254, 254));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("TÍTULO DE LA TABLA");
        titleLabel.setOpaque(true);

        exportBtn.setText("Exportar CSV");
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        orderByPointsBtn.setText("Por Puntos");
        orderByPointsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderByPointsBtnActionPerformed(evt);
            }
        });

        orderByNameBtn.setText("Por Nombre");
        orderByNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderByNameBtnActionPerformed(evt);
            }
        });

        sizeLabel.setBackground(new java.awt.Color(134, 33, 40));
        sizeLabel.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
        sizeLabel.setForeground(new java.awt.Color(254, 254, 254));
        sizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sizeLabel.setText("0000");
        sizeLabel.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(orderByPointsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderByNameBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exportBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exportBtn)
                    .addComponent(orderByPointsBtn)
                    .addComponent(orderByNameBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        export.exportCSV(bets);
    }//GEN-LAST:event_exportBtnActionPerformed

    private void orderByNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderByNameBtnActionPerformed
        cleanTable();
        sort.sortByGambler(bets);
        fillTable();
    }//GEN-LAST:event_orderByNameBtnActionPerformed

    private void orderByPointsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderByPointsBtnActionPerformed
        cleanTable();
        sort.sortByPoints(bets);
        fillTable();
    }//GEN-LAST:event_orderByPointsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mainTable;
    private javax.swing.JButton orderByNameBtn;
    private javax.swing.JButton orderByPointsBtn;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
